services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/dbname

  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: